on:
  push:
    branches: [main]

jobs:
  ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.ECR_REGION }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "webops/jakemulley-development"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:gha-$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:gha-$IMAGE_TAG
