on:
  push:
    branches: [main]

jobs:
  ecr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2 # Assume role in Cloud Platform
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}
      - uses: aws-actions/amazon-ecr-login@v1 # Login to the container repository
        id: login-ecr
      - run: | # Build and push a Docker image to the container repository
          docker build -t $REGISTRY/$REPOSITORY:gha-$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:gha-$IMAGE_TAG
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ var.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
